# Generated by Django 5.0.6 on 2024-12-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.IntegerField(null=True)),
                ("weight", models.IntegerField(null=True)),
                (
                    "ibw",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=5, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=5, null=True
                    ),
                ),
                (
                    "admission_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "reason_for_admission",
                    models.CharField(blank=True, default=None, null=True),
                ),
                (
                    "reason_for_ventilation",
                    models.CharField(blank=True, default=None, null=True),
                ),
                ("history_of_diabetes", models.BooleanField(default=False)),
                ("tags", models.CharField(blank=True, default=None, null=True)),
                ("history_of_bp", models.BooleanField(default=False)),
                ("current_status", models.CharField(blank=True, default="")),
                ("is_discharged", models.BooleanField(default=False)),
                (
                    "discharge_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ABGReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pH", models.FloatField()),
                ("pCO2", models.FloatField()),
                ("pO2", models.FloatField()),
                ("hCO3", models.FloatField()),
                ("base_excess", models.FloatField()),
                ("sO2", models.FloatField()),
                ("lactate", models.FloatField(default=0.0)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abg_reports",
                        to="patient.admissionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField()),
                ("added_by", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_advices",
                        to="patient.admissionrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patient_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                (
                    "blood_group",
                    models.CharField(default=None, max_length=10, null=True),
                ),
                (
                    "contact",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "aadhar",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "abha",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="authentication.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="admissionrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="patient.patient",
            ),
        ),
    ]
