name: jeevanconnect
description: "Cloud monitoring application for Jeevan devices"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  flutter_form_bloc: ^0.31.0
  objectbox: ^4.0.1
  http: ^1.2.1
  path_provider: ^2.1.3
  objectbox_flutter_libs: ^4.0.1
  intl: ^0.18.1
  webview_windows: ^0.4.0
  connectivity_plus: ^6.0.1
  fl_chart: ^0.68.0
  web_socket_channel: ^2.4.5
  collection: ^1.18.0
  async: ^2.11.0
  file_picker: ^8.0.6
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  objectbox_generator: ^4.0.1
  flutter_launcher_icons: "^0.13.1"
  msix: ^3.16.7

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48

msix_config:
  display_name: JeevanConnect
  publisher_display_name: Aerobiosys Innovations
  identity_name: aerobiosys.jeevanconnect.mvp
  msix_version: 1.0.0.0
  logo_path: D:\Aerobiosys\Products\JeevanConnect\source\desktop\jeevanconnect\assets\images\icon.png
  capabilities: internetClient, location
  store: false # Set to true to deploy to Microsoft Store
  icons_background_color: "#ffffff"
  architecture: x64
  certificate_path: CERTIFICATE.pfx
  certificate_password: Aero@2024

flutter:
  uses-material-design: true

  fonts:
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Mukta-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Mukta-Regular.ttf
          style: normal
        - asset: assets/fonts/Mukta-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Mukta-SemiBold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Mukta-Bold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/Mukta-ExtraBold.ttf
          weight: 900
          style: normal

  assets:
    - assets/audio/
    - assets/gif/
    - assets/images/
