# Generated by Django 5.0.6 on 2024-12-10 10:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="email address"),
                ),
                ("user_id", models.CharField(max_length=10, unique=True)),
                ("admin", models.BooleanField(default=False)),
                ("confirmed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "registered_id",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("contact", models.BigIntegerField(blank=True, null=True)),
                (
                    "emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "phone_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoginInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("browser", models.CharField(blank=True, max_length=50, null=True)),
                ("os", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("name", models.CharField(max_length=255)),
                (
                    "workspace_id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("registered_id", models.CharField(unique=True)),
                (
                    "email_id",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True, default=None, null=True)),
                ("contact", models.CharField(blank=True, default=None, null=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("archive", models.BooleanField(default=False)),
                (
                    "departments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True, related_name="admins", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "default_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="users", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="authentication.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceModeration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_member",
                    models.CharField(
                        choices=[("AD", "ADMIN"), ("AN", "ANYONE"), ("OW", "OWNER")],
                        default="OW",
                        max_length=2,
                    ),
                ),
                (
                    "edit_department",
                    models.CharField(
                        choices=[("AD", "ADMIN"), ("AN", "ANYONE"), ("OW", "OWNER")],
                        default="OW",
                        max_length=2,
                    ),
                ),
                (
                    "add_patient",
                    models.CharField(
                        choices=[("AD", "ADMIN"), ("AN", "ANYONE"), ("OW", "OWNER")],
                        default="AD",
                        max_length=2,
                    ),
                ),
                (
                    "edit_product",
                    models.CharField(
                        choices=[("AD", "ADMIN"), ("AN", "ANYONE"), ("OW", "OWNER")],
                        default="AD",
                        max_length=2,
                    ),
                ),
                (
                    "download_information",
                    models.CharField(
                        choices=[("AD", "ADMIN"), ("AN", "ANYONE"), ("OW", "OWNER")],
                        default="AN",
                        max_length=2,
                    ),
                ),
                (
                    "workspace_details",
                    models.CharField(
                        choices=[("AD", "ADMIN"), ("AN", "ANYONE"), ("OW", "OWNER")],
                        default="AN",
                        max_length=2,
                    ),
                ),
                (
                    "share_device",
                    models.CharField(
                        choices=[("AD", "ADMIN"), ("AN", "ANYONE"), ("OW", "OWNER")],
                        default="AD",
                        max_length=2,
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.workspace",
                    ),
                ),
            ],
        ),
    ]
