# Generated by Django 5.0.6 on 2024-12-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTicket",
            fields=[
                (
                    "ticket_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("booked_on", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BK", "Booked"),
                            ("UR", "Under review"),
                            ("IP", "In progress"),
                            ("CL", "Closed"),
                            ("DL", "Declined"),
                        ],
                        default="BK",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField()),
                (
                    "service_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="product.serviceticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ventilator",
            fields=[
                (
                    "serial_number",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Serial number",
                    ),
                ),
                ("lot_number", models.CharField(max_length=100)),
                ("manufactured_on", models.DateTimeField(null=True)),
                ("product_name", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("product_id", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "software_version",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "battery_serial_number",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "battery_manufacturing_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ID", "Idle"),
                            ("IU", "Active"),
                            ("RP", "In Service"),
                        ],
                        default="ID",
                        max_length=2,
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("is_on_service", models.BooleanField(default=False)),
                ("location", models.CharField(default=None, max_length=500, null=True)),
                ("department", models.CharField(blank=True, default=None, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventilators",
                        to="authentication.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ventilators",
            },
        ),
        migrations.AddField(
            model_name="serviceticket",
            name="ventilator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_tickets",
                to="product.ventilator",
            ),
        ),
    ]
